on:
  - push

name: Formatting & Linting
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup node 16
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm lint
        name: Run eslint
      - run: pnpm format:check
        name: Run formatting checks
